name: "Code quality"

on: [push, pull_request]

jobs:

  # flake:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout ğŸ›ï¸
  #       uses: actions/checkout@v2

  #     - name: Set up Python ğŸ”§
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.8'

  #     - name: Install dependencies ğŸ”§
  #       run: |
  #         python -m pip install --upgrade pip
  #         python -m pip install flake8
  #         pip install -e .['flake']
  #     - name: Test code quality ğŸ”§
  #       run: |
  #         flake8
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Black codestyle ğŸ”§
        uses: psf/black@stable